#!/usr/bin/env python

import rospy

from connector.ActionConnector import ActionConnector
from connector.config import config as c

if __name__ == '__main__':
    node_name = "action_connector"
    rospy.init_node(node_name, anonymous=False)

    conn = ActionConnector(c)

    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
