#!/usr/bin/env python

import rospy

from connector.connector_ import Connector
from connector.config import config as c

if __name__ == '__main__':
    node_name = "connector"
    rospy.init_node(node_name, anonymous=False)

    conn = Connector(c)

    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
