#!/usr/bin/env python

import rospy

from connector.state_connector import StateConnector
from connector.config import config as c

if __name__ == '__main__':
    node_name = "state_connector"
    rospy.init_node(node_name, anonymous=False)

    conn = StateConnector(c)

    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
